name    'fnerdwq-phpmyadmin'
version '0.0.1'
source 'https://github.com/fnerdwq/puppet-phpmyadmin.git'
author 'Frederik Wagner'
license 'Apache License, Version 2.0'
summary 'Puppet module managing PHPMyAdmin'
description 'Small module to manage PHPMyAdmin on Debian like systems'
project_page 'https://github.com/fnerdwq/puppet-phpmyadmin'

dependency 'puppetlabs/concat', '>= 1.1.0'
dependency 'puppetlabs/stdlib', '>= 1.0.0'
dependency 'puppetlabs/mysql', '>= 2.0.0'
